[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1f1f1f"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

